owner: peterkimzz
repo: upptime

sites:
  - name: peterkimzz.com
    url: http://peterkimzz.com

status-website:
  name: Upptime for peterkimzz.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: upptime.peterkimzz.com
